### PR TITLE
About me updated page

### PR DESCRIPTION
**Pull request by sophia-qin**
Changed code formatting and added a new user class in DataStore.

### CODE REVIEW

**Comment by jajanet** [comment]
hi sophia, for some reason this one shows there's a merge conflict too? maybe get that sorted out real quick then i'll approve it asap!!

**Comment by sophia-qin** [comment]
Fixed merge conflict!

**Comment by jajanet** [comment]
yay!!

**Comment by jajanet** [comment]
yay!!

**Comment by jajanet** [comment]
closed

**Comment by tylerhou** [comment]
Any reason why this PR is closed? It has unmerged commits.

**Pull request merged**
