### PR TITLE
Start Tag implementation

### PR DESCRIPTION
**Pull request by jajanet**
Data Properties:
- label as unique identifier
- set of places with that tag

Notes:
- followed these docs: https://cloud.google.com/appengine/docs/standard/java/datastore/jdo/relationships#many-to-many-relationships
    - might need to separate into `Tags` (which I think should only need a label property) and `PlaceTags` (which map tags to places and vice versa) as suggested by Tyler
    - Place would also need a Tags property (Set<Key> tags)
    - somewhat unrelated, but Places should have cascade delete if user is deleted maybe?
- not sure if casting retrieved taggedPlaces (Set<Key>) is correct in the entity constructor

### CODE REVIEW

**Comment by tylerhou** [comment]
Let's use PlaceTags -- so remove the Set. Again, it will make certain operations easier (with two sets, you have to update both the Place and the Tag when you want to add a tag to a place).

**Comment by tylerhou** [comment]
Otherwise, LGTM

**Comment by tylerhou** [comment]
(Also, please target master)

**Comment by jajanet** [comment]
Gonna close and recreate this PR since there's other file changes when i rebase it to master to avoid needing to fixing merge conflicts

**Pull request closed without merging**
