### PR TITLE
Location.java -> Place.java

### PR DESCRIPTION
**Pull request by jajanet**
rename location to place and make the class static

### CODE REVIEW

**Comment by tylerhou** [comment]
Please request a merge into your other PR.

Why does the class need to be static?

**Comment by jajanet** [comment]
> 
> 
> Please request a merge into your other PR.
> 
> Why does the class need to be static?

I was referencing the User class in the Datastore file and misunderstood what you meant by add static method on place. Also, how should I do that? When I go to edit it, it looks like rebasing and I'm sure we don't wanna do that

**Comment by tylerhou** [comment]
Okay it looks like you already merged your other PR. So this one is fine to merge into master.

**Comment by tylerhou** [comment]
> How should I do that? When I go to edit the branch to merge into, the prompt looks like it's asking me if I want to rebase the repo.

Not sure what you mean here; for me it just changes the branch.

> Not sure what it means exactly though and could be misunderstnading, just wanna be careful and not screw things up

Changing the base branch won't mutate the repo so it can't mess anything up.

**Pull request merged**
